### ISSUE TITLE
Node v0.12.x compatibility

### ISSUE THREAD

**Issue by Floby** [kanso/kanso#424] opened 2015-02-23 10:18 UTC
It seems that Kanso cannot operate on node.js v0.12.

It first breaks on `/lib/utils.js` line 14 when requiring process.bindings('evals'). But I suspect there are other adaptations needed.

Are there any plans to support 0.12 ?

**Comment by garethbowen** [comment] 2015-02-23 19:14
Hi @Floby. This is a duplicate of #422 and the PR #423. I (or someone else) will get on to this soon.

**Comment by garethbowen** [comment] 2015-02-24 02:28
Closing as duplicate.

**Closed by garethbowen** 2015-02-24 02:28 UTC
